export default {
    rules: {
      'no-console': 'error',
      'no-alert': 'error',
      'no-debugger': 'error',
      'no-undef': 'error',
      'no-use-before-define': 'error',
      'prefer-const': 'error',
      'no-var': 'error',
      'no-new-object': 'error',
      'no-array-constructor': 'error',
      'no-empty-function': 'error',
      'no-multi-str': 'error',
      'no-multi-spaces': 'error',
      'no-multiple-empty-lines': 'error',
      'no-new-wrappers': 'error',
      'no-eval': 'error',
      'no-implied-eval': 'error',
      'no-new-func': 'error',
      'no-loop-func': 'error',
      'no-with': 'error',
      'no-shadow': 'error',
      'no-label-var': 'error',
      'no-lonely-if': 'error',
      'no-else-return': 'error',
      'no-useless-return': 'error',
      'no-eq-null': 'error',
      'no-implicit-globals': 'error',
      'no-new': 'error',
      'no-octal': 'error',
      'no-redeclare': 'error',
      'no-return-assign': 'error',
      'no-self-assign': 'error',
      'no-self-compare': 'error',
      'no-sequences': 'error',
      'no-unmodified-loop-condition': 'error',
      'no-unused-expressions': 'error',
      'no-unused-labels': 'error',
      'no-useless-catch': 'error',
      'no-useless-concat': 'error',
      'no-useless-escape': 'error',
      'no-useless-rename': 'error',
      'no-useless-computed-key': 'error',
      'no-useless-constructor': 'error',
      'no-whitespace-before-property': 'error',
      'prefer-destructuring': ['error', { object: true, array: false }],
      'require-await': 'error',
      'semi': ['error', 'always'],
      'space-before-blocks': 'error',
      'space-before-function-paren': ['error', 'never'],
      'space-in-parens': ['error', 'never'],
      'quotes': ['error', 'double'],
    },
  };
  